name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: fintrack_user
          POSTGRES_PASSWORD: fintrack_pass
          POSTGRES_DB: fintrack_pro_test
        ports:
          - 5433:5432
        options: >-
          --health-cmd "pg_isready -U fintrack_user -d fintrack_pro_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma Client
        run: npm run generate
        env:
          DATABASE_URL: postgres://fintrack_user:fintrack_pass@localhost:5433/fintrack_pro_test

      - name: Apply migrations to test DB
        run: npm run migrate:deploy
        env:
          DATABASE_URL: postgres://fintrack_user:fintrack_pass@localhost:5433/fintrack_pro_test

      - name: Run unit tests
        run: npm run test:unit

      - name: Run integration tests
        env:
          NODE_ENV: test
          ENV_PATH: .env.test
          DATABASE_URL: postgres://fintrack_user:fintrack_pass@localhost:5433/fintrack_pro_test
        run: npm run test:integration

  frontend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build
